# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: klaus@eckelt.info
author_name: Klaus Eckelt
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: frontend
labextension_name: jupyterlab-ascii-homer
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: jupyterlab-ascii-homer
repository: https://github.com/keckelt/jupyterlab-ascii-homer
test: true
viewer_name: ''

